-- Data source: Snowflake
WITH BUSINESSES AS (
SELECT BUSINESS_ID, MAX(BUSINESS_NAME) AS BUSINESS_NAME
FROM PRODDB.PUBLIC.DIMENSION_STORE 
GROUP BY BUSINESS_ID
)

select ITEM_NAME
     , ifnull(DD_SIC, 'NULL') as DD_SIC
     , CONCAT_WS(' > ', AISLE_NAME_L1, AISLE_NAME_L2) as BROWSE_CATEGORY
     , CAST(PARSE_JSON(TRAITS)['Size'] AS STRING) AS SIZE
     , PHOTO_URL
     , PRODUCT_CATEGORY_ID
     , ifnull(T.PATH, 'NULL') AS PRODUCT_CATEGORY
     , BRAND_ID
     , COALESCE(concat_ws(' > ', B.BRAND_NAME_L1, B.BRAND_NAME_L2), B.BRAND_NAME_L1, 'NULL') AS BRAND
     , ARRAY_TO_STRING(ARRAY_COMPACT(UPC), ', ') as UPC
     , ARRAY_TO_STRING(ARRAY_COMPACT(GTIN_14), ', ') as GTIN_14
     , ifnull(UNIT, 'NULL') AS PURCHASE_UNIT 
     , ifnull(SCAN_STRATEGY, 'NULL') as SCAN_STRATEGY
     , case when PURCHASE_TYPE = 1 then 'UNIT'
            when PURCHASE_TYPE = 2 then 'MEASUREMENT'
            when PURCHASE_TYPE = 3 then 'UNIT_TO_MEASUREMENT'
            else 'NULL'
        end as PURCHASE_TYPE
     , ifnull(ROUND(APPROXIMATE_SOLD_AS_QUANTITY, 2)::varchar, 'NULL') as APPROXIMATE_SOLD_AS_QUANTITY
     , ifnull(APPROXIMATE_SOLD_AS_UNIT::varchar, 'NULL') as APPROXIMATE_SOLD_AS_UNIT
     , ifnull(EXTERNAL_INFORMATION:COMPLIANCE:RESTRICTION_TYPE:VALUE::varchar, 'NULL') AS RESTRICTION_TYPE
     , DD_BUSINESS_ID,
     CONCAT(CONCAT(CONCAT(BUSINESS_ID,' ('),BUSINESS_NAME),')') AS BUSINESS
     , ifnull(DETAIL, 'NULL') AS DESCRIPTION
  from CATALOG_SERVICE_PROD.PUBLIC.PRODUCT_ITEM P
  left join PRODDB.STATIC.DD_TAXONOMY_SOT T
    on P.PRODUCT_CATEGORY_ID = T.ID 
  left join CATALOG_SERVICE_PROD.PUBLIC.DENORMALIZED_BRAND B
    on P.BRAND_ID = B.PATH_ID
  JOIN BUSINESSES 
    ON BUSINESSES.BUSINESS_ID=DD_BUSINESS_ID
 where 1=1
   and MERCHANT_SUPPLIED_ID = '{{search_item_msid}}'